# Generated by Django 5.1.5 on 2025-03-17 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stock', models.IntegerField()),
                ('Product_type', models.CharField(max_length=100)),
                ('Created_at', models.DateField()),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Attribute',
            fields=[
                ('Attribute_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Attribute', models.CharField(max_length=100)),
                ('Value', models.IntegerField()),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Varient',
            fields=[
                ('Varient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Attribute', models.CharField(max_length=100)),
                ('Value', models.IntegerField()),
                ('Extra_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Image1', models.ImageField(upload_to='product_images/')),
                ('Image2', models.ImageField(upload_to='product_images/')),
                ('Image3', models.ImageField(upload_to='product_images/')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
