# Generated by Django 5.1.5 on 2025-03-17 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Attribute',
            new_name='ProductAttribute',
        ),
        migrations.RenameModel(
            old_name='Product_Varient',
            new_name='ProductVarient',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Category_id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category_id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_type',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Stock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='Attribute',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='Attribute_id',
            new_name='attribute_id',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='Product_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='Value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='productvarient',
            old_name='Attribute',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='productvarient',
            old_name='Extra_Price',
            new_name='extra_price',
        ),
        migrations.RenameField(
            model_name='productvarient',
            old_name='Image1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='productvarient',
            old_name='Image2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='productvarient',
            old_name='Image3',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='productvarient',
            old_name='Product_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productvarient',
            old_name='Value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='productvarient',
            old_name='Varient_id',
            new_name='varient_id',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_Category',
        ),
    ]
