# Generated by Django 5.1.7 on 2025-03-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_digitalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarient',
            name='discount_per',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvarient',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvarient',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
