# Generated by Django 5.1.7 on 2025-03-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productvarient_discount_per_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
