# Generated by Django 5.1.7 on 2025-03-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_product_price_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarient',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
