# Generated by Django 5.1.7 on 2025-03-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productvarient_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
