# Generated by Django 5.1.7 on 2025-03-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='attribute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
