# Generated by Django 5.1.7 on 2025-03-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_productvarient_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='extra_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
