# Generated by Django 5.1.7 on 2025-03-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_productsizeoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_category',
            new_name='parent_category',
        ),
    ]
