# Generated by Django 5.1.7 on 2025-03-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_sub_category_category_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarient',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='image3',
        ),
    ]
