# Generated by Django 5.1.7 on 2025-03-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_productvarient_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarient',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productvarient',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productvarient',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
