# Generated by Django 5.1.7 on 2025-03-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_productvarient_image1_productvarient_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarient',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productvarient',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
