# Generated by Django 5.1.7 on 2025-04-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_productvarient_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarient',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
