# Generated by Django 5.1.7 on 2025-04-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_productvarient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='image1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='image2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='image3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
