# Generated by Django 5.1.7 on 2025-04-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_productvarient_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvarient',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
