# Generated by Django 5.1.7 on 2025-03-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
