# Generated by Django 5.1.7 on 2025-03-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customusermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
