# Generated by Django 5.1.7 on 2025-03-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customusermodel_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='otp_expiry',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
